//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual seller seller { get; set; }
    }
}
